-- ACCOUNTS TABLE
-- Stores each account
CREATE TABLE accounts (

    -- Unique ID automatically generated by PostgreSQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Account name must exist, cannot be empty, and cannot be duplicated
    name TEXT NOT NULL UNIQUE CHECK (length(name) > 0),

    -- Timestamp used for soft deletion
    deleted_at TIMESTAMPTZ
);


-- CATEGORIES TABLE
-- Stores transaction categories
CREATE TABLE categories (

    -- Unique ID automatically generated by PostgreSQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Category name must exist, cannot be empty, and cannot be duplicated
    name TEXT NOT NULL UNIQUE CHECK (length(name) > 0)
);


-- TRANSACTIONS TABLE
-- Stores money entering or leaving an account
CREATE TABLE transactions (

    -- Unique ID automatically generated by PostgreSQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Account this transaction belongs to
    account_id INTEGER NOT NULL REFERENCES accounts(id),

    -- Transaction name
    name TEXT NOT NULL CHECK (length(name) > 0),

    -- Positive = money in, negative = money out, zero not allowed
    amount NUMERIC(12,2) NOT NULL CHECK (amount != 0),

    -- Date the transaction actually occurred
    transaction_date DATE NOT NULL,

    -- Timestamp when the transaction was created
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Timestamp when the transaction was last updated
    updated_at TIMESTAMPTZ,

    -- Optional category for the transaction
    category_id INTEGER REFERENCES categories(id),

    -- Timestamp used for soft deletion
    deleted_at TIMESTAMPTZ
);