-- ACCOUNTS TABLE
-- Stores each account
CREATE TABLE accounts (

    -- Unique ID automatically generated by PostgreSQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Account name must exist, cannot be empty, and cannot be duplicated.
    name TEXT NOT NULL UNIQUE CHECK (length(name) > 0),

    -- This stores when an account was deleted as so that we can soft delete any transactions
    deleted_at TIMESTAMPTZ 
);

-- CATEGORIES TABLE
-- Categories of expenses in the personal finances transaction table
CREATE TABLE categories (

    -- Category ID and must be unique
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Category name
    name TEXT NOT NULL CHECK (length(name) > 0) UNIQUE
);


-- TRANSACTIONS TABLE
-- Stores money entering or leaving an account.
CREATE TABLE transactions (

    -- Unique ID automatically generated by PostgreSQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Foreign id that links transaction to the account.
    account_id INTEGER NOT NULL REFERENCES accounts(id),

    -- Transac name
    name TEXT NOT NULL CHECK (length(name) > 0),

    -- Positive means money in negative means money out and zeo not allowed
    amount NUMERIC(12,2) NOT NULL CHECK (amount != 0),

    -- Storing transaction date, we need to know this. This is separate from created time becasue created is hwen the user enters it
    transaction_date DATE NOT NULL,

    -- Created when?
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Updated when
    updated_at TIMESTAMPTZ,

    -- Categories
    category_id INTEGER NOT NULL REFERENCES categories(category_id),

    -- Deleted save time stamp
    deleted_at TIMESTAMPTZ,


    -- What happens to transactions when account is deleted?
    -- i don't know
);

